### ISSUE TITLE
Preprocessing breaks items `Log - Event - Errors & Warnings` and `Log - Event - Errors only`

### ISSUE THREAD

**Issue by cristoslc** [soliantconsulting/FileMaker-Server-Zabbix-Templates#3]
The Windows template items `Log - Event - Errors & Warnings` and `Log - Event - Errors only` did not work and threw an error in Zabbix 4.4 related to preprocessing:
```
Preprocessing failed for: The description for Event ID:3001 in Source:'FileMaker Server 18' cannot be found. Either the com...
1. Failed: cannot perform regular expression "^(.*\tError\t.*)$" match for value of type "string": pattern does not match
```

Removing the preprocessing component from the Item appears to have fixed the problem. (I also happened to change the mode from `skip` to `all` in order to get it to process older entries, but I'm not certain whether that was a necessary step since `Log - Event` works just fine with the mode set to `skip`.)

**Comment by wimdecorte** [comment]
The fix is to leave the pre-processing in place but to make sure the "custom on fail" checkbox is set on the pre-processing item, with the default action of discard.
That will make sure that the item remains in enabled state and doesn't go to "unsupported" state.
This will be fixed in the next release.
